exports.up = async function (knex) {
  return knex.schema.createTable('сonstructors', function (table) {
    table.increments('id').primary()
    table.text('product').notNullable().unique()
    table.text('core_constructor_product').notNullable()
    table.text('archive_materials1').notNullable()
    table.text('archive_materials2').notNullable()
    table.text('archive_materials3').notNullable()
    table.text('archive_tools1').notNullable()
    table.text('archive_tools2').notNullable()
    table.text('archive_tools3').notNullable()
    table.text('archive_hypotheses1').notNullable()
    table.text('archive_hypotheses2').notNullable()
    table.text('archive_hypotheses3').notNullable()
    table.text('archive_head_metrics_prototype1').notNullable()
    table.text('archive_head_metrics_prototype2').notNullable()
    table.text('archive_head_metrics_prototype3').notNullable()
    table.text('archive_prototyping_laboratory1').notNullable()
    table.text('archive_prototyping_laboratory2').notNullable()
    table.text('archive_prototyping_laboratory3').notNullable()
    table.text('archive_experiment_library1').notNullable()
    table.text('archive_experiment_library2').notNullable()
    table.text('archive_experiment_library3').notNullable()
    table.text('archive_product_testing1').notNullable()
    table.text('archive_product_testing2').notNullable()
    table.text('archive_product_testing3').notNullable()
    table.text('archive_product_main_metrics1').notNullable()
    table.text('archive_product_main_metrics2').notNullable()
    table.text('archive_product_main_metrics3').notNullable()
    table.text('archive_investments1').notNullable()
    table.text('archive_investments2').notNullable()
    table.text('archive_investments3').notNullable()
    table.text('archive_legislative_foundation1').notNullable()
    table.text('archive_legislative_foundation2').notNullable()
    table.text('archive_legislative_foundation3').notNullable()
    table.text('archive_launch_enterprise1').notNullable()
    table.text('archive_launch_enterprise2').notNullable()
    table.text('archive_launch_enterprise3').notNullable()
    table.text('launch_shchus_hub').notNullable()

    table.text('overlook_product_video').notNullable()
    table.text('overlook_constructor_video').notNullable()
    table.text('archive_materials').notNullable()
    table.text('archive_tools').notNullable()
    table.text('archive_hypotheses').notNullable()
    table.text('pitch_prototype_video').notNullable()
    table.text('archive_head_metrics_prototype').notNullable()
    table.text('laboratory_experiments_video').notNullable()
    table.text('archive_prototyping_laboratory').notNullable()
    table.text('archive_experiment_library').notNullable()
    table.text('archive_product_testing').notNullable()
    table.text('pitch_product_video').notNullable()
    table.text('archive_product_main_metrics').notNullable()
    table.text('archive_investments').notNullable()
    table.text('archive_legislative_foundation').notNullable()
    table.text('archive_launch_enterprise').notNullable()

    table.timestamp('created_at').defaultTo(knex.fn.now())
    table.timestamp('updated_at').defaultTo(knex.fn.now())
  })
}

exports.down = async function (knex) {
  return knex.schema.dropTable('сonstructors')
}
